language: generic

sudo: required

# before_install:
#   - docker build -t megajon/megajon-web-api -f ./Dockerfile .

# script:
#   - docker run -e CI=true megajon/megajon-web-api npm  test -- --coverage

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
